"""
Dimension Products ETL
Populates dim_products table with product data
"""
import sys
import os
import json
from pyspark.sql import DataFrame
from pyspark.sql.functions import col, lit
import pyspark.sql.types as T

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from batch_processing.etl.base_etl import BaseETL


class DimProductsETL(BaseETL):
    """ETL job for populating dim_products dimension table"""

    def __init__(self):
        super().__init__("DimProducts")

    def extract(self) -> DataFrame:
        """
        Extract product data from generated products file

        Returns:
            DataFrame: Product data
        """
        # Read from products.json file generated by data generation
        products_file = "data/raw/products.json"

        if not os.path.exists(products_file):
            print(f"Warning: Products file not found at {products_file}")
            print("Creating sample products DataFrame")
            # Create sample products
            data = [
                (f"PROD_{i:08d}", f"Product {i}", "Electronics", 99.99)
                for i in range(1, 11)
            ]
            df = self.spark.createDataFrame(data, ["product_id", "name", "category", "price"])
            return df

        # Read JSON file - it's an array format
        df = self.spark.read.option("multiline", "true").json(products_file)

        return df

    def transform(self, df: DataFrame) -> DataFrame:
        """
        Transform product data to dimension format with SCD Type 2

        Args:
            df: Input DataFrame

        Returns:
            DataFrame: Transformed product dimension with SCD Type 2 columns
        """
        from pyspark.sql.functions import current_timestamp

        # Transform to match dim_products schema
        transformed_df = df.select(
            col("product_id"),
            col("name").alias("product_name"),
            col("category"),
            lit(None).cast("string").alias("subcategory"),
            col("price").alias("base_price"),
            (col("price") * 0.6).alias("cost"),  # Assume 40% margin
            (col("price") * 0.4).alias("margin"),
            lit(True).alias("is_active"),
            current_timestamp().alias("effective_start_date"),
            lit("9999-12-31 23:59:59").cast("timestamp").alias("effective_end_date"),
            lit(True).alias("is_current")
        )

        return transformed_df

    def load(self, df: DataFrame) -> None:
        """
        Load product dimension to warehouse using SCD Type 2

        Args:
            df: Transformed DataFrame
        """
        if df.count() > 0:
            self.write_to_warehouse(
                df,
                "dim_products",
                mode="append",
                scd_type2=True,
                natural_key="product_id"
            )
            print(f"  Loaded {df.count()} product records to dim_products")
        else:
            print("  No products to load (products file not found)")


if __name__ == "__main__":
    # Run DimProducts ETL
    etl = DimProductsETL()
    etl.run()
